project:
  name: NoxEngine
  description: A C++ OpenGL 2D/3D Engine
  version: 1.0.0
  author: NoxFly
  url: https://github.com/NoxFly/NoxEngine
  license: AGPL-3.0

config:
  mode: 1
  type: cpp
  cppVersion: 20
  guard: ifndef
  flags: -Wall -Wextra

dependencies:
  GLEW: libglew-dev
  GLM: libglm-dev
  OpenGL: libglu1-mesa-dev
  SDL2: libsdl2-dev
  SDL2_image: libsdl2-image-dev
  SDL2_ttf: libsdl2-ttf-dev

